name: Testing on various Java versions on Linux, Windows, and MacOS

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        jdk: [ 17, 25 ]
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Store test results
      if: failure()
      uses: actions/upload-artifact@v7
      with:
        name: test-results
        path: build/reports
